---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: xray-daemon
  name: xray-daemon
  namespace: x-ray

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: xray-daemon
  labels:
    app: xray-daemon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: xray-daemon
  namespace: x-ray

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: xray-daemon
  namespace: x-ray
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xray-daemon
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: xray-config
      - name: credentials
        secret:
          secretName: "credentials"
      hostNetwork: true
      containers:
      - name: xray-daemon
        image: ldelgadop/xray
        imagePullPolicy: Always
        command: [ "/usr/bin/xray", "-c", "/aws/xray/config.yaml", "-b", "0.0.0.0:2000", "-t", "0.0.0.0:2000" ]
        resources:
          limits:
            memory: 256Mi
        ports:
        - name: xray-ingest
          containerPort: 2000
          hostPort: 2000
          protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /aws/xray
          readOnly: true
        - name: credentials
          mountPath: /root/.aws/
          readOnly: true

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: x-ray
data:
  config.yaml: |-    
    TotalBufferSizeMB: 64
    Region: "us-west-2"
    Socket:
      UDPAddress: 0.0.0.0:2000
    Logging:
      LogRotation: true
      LogLevel: debug
    LocalMode: false
    NoVerifySSL: false
    ProxyAddress: ""
    Version: 1

---

apiVersion: v1
kind: Service
metadata:
  name: xray-service
  namespace: x-ray
spec:
  selector:
    app: xray-daemon
  clusterIP: None
  ports:
  - name: incoming
    port: 2000
    protocol: UDP

---