---

apiVersion: v1                                                                                                                                                                                                                              
kind: Service                                                                                                                                                                                                                               
metadata:                                                                                                                                                                                                                                   
  name: x-ray-sample-backend-k8s                                                                                                                                                                                                            
  namespace: x-ray                                                                                                                                                                                                                          
spec:                                                                                                                                                                                                                                       
  ports:                                                                                                                                                                                                                                    
    - port: 80                                                                                                                                                                                                                              
      targetPort: 8080                                                                                                                                                                                                                      
  selector:                                                                                                                                                                                                                                 
    app: x-ray-sample-backend-k8s                                                                                                                                                                                                           
    tier: backend

---
                                                                                                                                                                                                                                         
apiVersion: apps/v1                                                                                                                                                                                                                         
kind: Deployment                                                                                                                                                                                                                            
metadata:                                                                                                                                                                                                                                   
  name: x-ray-sample-backend-k8s                                                                                                                                                                                                            
  namespace: x-ray                                                                                                                                                                                                                          
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: x-ray-sample-backend-k8s
      tier: backend
  template:
    metadata:
      labels:
        app: x-ray-sample-backend-k8s
        tier: backend
    spec:
      containers:
        - name: x-ray-sample-backend-k8s
          image: ldelgadop/example-backend-go
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080

---
