apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.9.1_coreos.0
    command:
    - /hyperkube
    - apiserver
    - '--bind-address=0.0.0.0'
    - '--etcd-servers=http://192.168.1.224:2379,http://192.168.1.223:2379,http://192.168.1.227:2379'
    - '--storage-backend=etcd2'
    - '--allow-privileged=true'
    - '--service-cluster-ip-range=10.252.0.0/24'
    - '--secure-port=443'
    - '--advertise-address=192.168.1.224'
    - '--admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,ResourceQuota'
    - '--tls-cert-file=/etc/kubernetes/ssl/apiserver.pem'
    - '--tls-private-key-file=/etc/kubernetes/ssl/apiserver-key.pem'
    - '--client-ca-file=/etc/kubernetes/ssl/ca.pem'
    - '--service-account-key-file=/etc/kubernetes/ssl/apiserver-key.pem'
    - '--runtime-config=extensions/v1beta1/networkpolicies=true'
    - '--anonymous-auth=false'
    - '--apiserver-count=2'
    - '--requestheader-client-ca-file=/etc/kubernetes/ssl/ca.pem'
    - '--requestheader-username-headers=X-Remote-User'
    - '--requestheader-group-headers=X-Remote-Group'
    - '--requestheader-extra-headers-prefix=X-Remote-Extra'
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 5
      timeoutSeconds: 2
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /var/log/
    name: kube-apiserver-log
